### PR TITLE
Npf

### PR DESCRIPTION
**Pull request by mneumann177**
Adds support for multiple pseudofermion fields in the RHMC as an inputfile parameter. This can be used to optimize the RHMC performance and enables the simulation of No. flavors >= 4. Also the remez is updated to support noninteger No. flavors.
Also 1f was renamed to sf and 2f to lf, since numbers now indicate the elements of a Spinorfield_container (and the respective masses were already named ms and ml anyway, it looks like 1f and 2f were named that way for historic reasons from the remez code).

no_pf is set to 1 per default, so if you don't use this feature, nothing changes at all.

make everything and all test (at least the ones which are working in main) pass.

### CODE REVIEW

**Review by luhuhis — CHANGES_REQUESTED** [review]
Please add documentation and add a test routine that tests the new functionality (or add it to the rhmc test)

**Comment by mneumann177** [comment]
test routine added and docs written. Also fixed the old rhmc_test.

**Comment by lukas-mazur** [comment]
Very good! Have you checked whether the performance of the default RMHC in this branch is the same compared to the one in the main branch?

**Comment by mneumann177** [comment]
I did some quick tests with a 12^3x6 lattice and Nf=pi+0 (The main branch can already do noninteger Nf<4 if you use a ratapprox from the new remez). All runs started from the same configuration.

Compared to main, no_pf=1 runs 3.5% faster (can someone check this? I would have expected no change).
Note that when is comes to time/acceptance there is a "sweet spot" of no_pf (depending on the Nf you are using), which is for Nf=pi at no_pf=2, resulting in a 35% speed boost.



[speedup.pdf](https://github.com/LatticeQCD/SIMULATeQCD/files/7833110/speedup.pdf)
[time_per_accept.pdf](https://github.com/LatticeQCD/SIMULATeQCD/files/7833111/time_per_accept.pdf)

**Comment by clarkedavida** [comment]
Without changing any parameters, on p001, main branch RHMC takes 1m51s for 2 reversibility checks and 10 HMC updates. Npf branch RHMC takes 1m56s for the same. I guess this is not exactly the same text Marius did, but I would like to merge this.

**Comment by clarkedavida** [comment]
There was ample time to object, and it looks reasonable to me, so I will merge.

**Pull request merged**
