### PR TITLE
Testing/link by link

### PR DESCRIPTION
**Pull request by dbollweg**
Rewrote rhmc/smearing/force tests to check results link by link versus reference configs/results

### CODE REVIEW

**Comment by clarkedavida** [comment]
Can you tell me a bit about the imaginary mu checks? I guess you are comparing the results there also with the parallelgpucode?

The only issue with comparing the imaginary mu stuff with the parallelgpucode is that we are not yet 100% sure that code is correct... We are still looking into it.

**Comment by dbollweg** [comment]
I'm testing imaginary mu stuff against the state of the parallelgpucode/the current state of this repo (i.e. we will only notice deviations from here on out). In case of the smearing, the test is in my opinion completely redundant because all that is done is literally just multiplying the temporal links with  +/- an additional phase. The force is tested in the same fashion, using the current state as a reference. I am not sure at this point whether is reference is correct? Maybe we can discus this in the next call and get Christians opinion. He mentioned something about taking out the phase at some point and I am not sure if this is taken care of.

**Comment by clarkedavida** [comment]
The "taking out the phase thing" I think is something that used to be necessary for the BielefeldGPUCode, but is not necessary anymore with parallelgpucode or SIMULATeQCD.

I would say once we have settled on whether SIMULATeQCD imaginary mu or parallelgpucode imaginary mu is correct, we can make any corresponding changes here if necessary and merge this branch in.

**Comment by clarkedavida** [comment]
The SIMULATeQCD code is the correct code. So if for these tests you are using current SIMULATeQCD as a reference, we should be good. If you confirm I understood that correctly I'll merge it in.

**Comment by dbollweg** [comment]
Yes, the current state of SIMULATeQCD is used as the reference here.

**Pull request merged**
