### PR TITLE
Hip and cuda

### PR DESCRIPTION
**Pull request by lukas-mazur**
# This branch adds support for HIP on NVIDIA and AMD plattforms. 

## Important notes
- `CMakelist.txt` has changed a lot to support both, CUDA and HIP.
- Renamed `USE_CUDA_AWARE_MPI` to `USE_GPU_AWARE_MPI` in `CMakelist.txt`.
- Renamed `USE_CUDA_P2P` to `USE_GPU_P2P` in `CMakelist.txt`.
- Added optional parameter `BACKEND`, which can be set to `"cuda"` (default), `"hip_nvidia"` or `"hip_amd"`.
- All `*.cu` files have been renamed to `*.cpp`. The CMakelist has now an additional function called `set_SIMULATeQCD_gpu_backend` to specify whether a `*.cpp` file includes device code or not.
- HIP calls have been added.
- The clang compiler showed a lot of `nodiscard` warnings. I have fixed them.
- New global defines have been introduced, called `__GPU_ARCH__` and `__GPUCC__` to identify device vs host compilation.
- P2P support is only available by the CUDA backend. The HIP backend does not support that yet and `cmake` will throw an error if you try to activate it.
- Half precision only works with CUDA. The HIP backend does not support that yet.
- Documentation includes now guidelines to build the source for HIP platforms.

### Building source with CUDA
```shell
cmake ../simulateqcd/ \
-DARCHITECTURE="70" \
-DUSE_GPU_AWARE_MPI=ON \
-DUSE_GPU_P2P=ON \
``` 
### Building source with HIP for NVIDIA plattforms (Experimental)
```shell
cmake ../simulateqcd/ \
-DARCHITECTURE="70" \
-DUSE_GPU_AWARE_MPI=ON \
-DUSE_GPU_P2P=OFF \
-DBACKEND="hip_nvidia" \
``` 
(more details can be found in the documentation)
### Building source with HIP for AMD plattforms (Experimental)
```shell
cmake ../simulateqcd/ \
-DARCHITECTURE="gfx906,gfx908" \
-DUSE_GPU_AWARE_MPI=ON \
-DUSE_GPU_P2P=OFF \
-DBACKEND="hip_amd" \
``` 
(more details can be found in the documentation)

## Before we merge
If you have access to an HIP plattform and could test the code there, that would be awesome! I ran all tests on single GPU with hip_nvidia and they seem to be fine. 
However, the HIP backend is still experimental. HIPs cmake support is not so advanced yet. So it might be that on some systems, some HIP paths are not found automatically by cmake. In these cases please report which paths are incorrect.

But No. 1 priority is that the CUDA backed works without issues. I also ran all tests on single GPU with cuda and they seem to be fine. Please perform multi-gpu tests at least for the CUDA backend and let me know if something does not work out.

Cheers,
Lukas

### CODE REVIEW

**Comment by clarkedavida** [comment]
On Pascal GPUs I am finding the `MixedPrecInverter` test to fail. In particular with
```
# [2022-01-30 20:11:23] INFO: Initializing MPI with (4 proc)
# [2022-01-30 20:11:23] INFO: Reading parameters from file :: ../parameter/tests/MixedPrecInverterTest.param
# [2022-01-30 20:11:23] INFO: # PARAM :: Lattice = 64 64 64 32 
# [2022-01-30 20:11:23] INFO: # PARAM :: Nodes = 2 2 1 1 
```
I get the error
```
# [2022-01-30 20:11:23] INFO: > Is MPI CUDA-aware? @compilation YES, @runtime YES
# [2022-01-30 20:11:23] INFO: > GPU compute capability: 60
^[[0;33m# [2022-01-30 20:11:23] WARN: Cannot determine for which compute capability the code was compiled!^[[0m
# [2022-01-30 20:11:23] DEBUG: > Collecting neighbor information...
# [2022-01-30 20:11:23] INFO: [Rank 1] > p001 CPU_0 GPU_5; MPI: world_rank=1, node_rank=1, coord: ( 0 1 0 0 )
# [2022-01-30 20:11:23] INFO: [Rank 2] > p001 CPU_0 GPU_5; MPI: world_rank=2, node_rank=2, coord: ( 1 0 0 0 )
# [2022-01-30 20:11:23] INFO: [Rank 3] > p001 CPU_0 GPU_5; MPI: world_rank=3, node_rank=3, coord: ( 1 1 0 0 )
# [2022-01-30 20:11:23] DEBUG: > Neighbor information collected!
# [2022-01-30 20:11:23] INFO: > Checking support for P2P (Peer-to-Peer) and UVA (Unified Virtual Addressing):
# [2022-01-30 20:11:23] INFO: [Rank 0] > p001 GPU_5(Tesla P100-SXM2-16GB): P2P YES; UVA YES
# [2022-01-30 20:11:23] INFO: [Rank 1] > p001 GPU_5(Tesla P100-SXM2-16GB): P2P YES; UVA YES
# [2022-01-30 20:11:23] INFO: [Rank 2] > p001 GPU_5(Tesla P100-SXM2-16GB): P2P YES; UVA YES
# [2022-01-30 20:11:23] INFO: Initialize Indexer with HaloDepth = 4^[[0;33m^[[0m
# [2022-01-30 20:11:23] INFO: [Rank 3] > p001 GPU_5(Tesla P100-SXM2-16GB): P2P YES; UVA YES
# [2022-01-30 20:11:24] DEBUG: [Rank 0] Local size without Halos: 32 32 64 32
# [2022-01-30 20:11:24] DEBUG: [Rank 1] Local size without Halos: 32 32 64 32
# [2022-01-30 20:11:24] DEBUG: [Rank 0] Local size with Halos: 40 40 64 32
# [2022-01-30 20:11:24] INFO: Running mixed precision inverter test
# [2022-01-30 20:11:24] INFO: testing float-half
# [2022-01-30 20:11:24] DEBUG: [Rank 2] Local size without Halos: 32 32 64 32
# [2022-01-30 20:11:24] DEBUG: [Rank 2] Local size with Halos: 40 40 64 32
# [2022-01-30 20:11:24] DEBUG: [Rank 1] Local size with Halos: 40 40 64 32
# [2022-01-30 20:11:24] DEBUG: [Rank 3] Local size without Halos: 32 32 64 32
# [2022-01-30 20:11:24] DEBUG: [Rank 3] Local size with Halos: 40 40 64 32
^[[1;31m# [2022-01-30 20:11:25] FATAL: [Rank 0] A GPU error occured: _rawPointer: Failed to allocate 0.764412 GB of memory on device: out of memory ( cudaErrorMemoryAllocation )^[[0m
^[[1;31m# [2022-01-30 20:11:25] FATAL: [Rank 1] A GPU error occured: _rawPointer: Failed to allocate 0.764412 GB of memory on device: out of memory ( cudaErrorMemoryAllocation )^[[0m
^[[1;31m# [2022-01-30 20:11:25] FATAL: [Rank 2] A GPU error occured: _rawPointer: Failed to allocate 0.764412 GB of memory on device: out of memory ( cudaErrorMemoryAllocation )^[[0m
^[[1;31m# [2022-01-30 20:11:25] FATAL: [Rank 3] A GPU error occured: _rawPointer: Failed to allocate 0.764412 GB of memory on device: out of memory ( cudaErrorMemoryAllocation )^[[0m
# [2022-01-30 20:11:25] INFO: Finalize CommunicationBase
^[[0;31m# [2022-01-30 20:11:25] ERROR: There has been a runtime error!^[[0m
```

Lukas, maybe you should check whether all the multi-GPU tests also pass on influx.

**Comment by lukas-mazur** [comment]
I just ran the same tast on the pascal node and it passed:
```Shell
lmazur@p001:~/simulateqcd/build2/testing$ mpiexec -n 4 ./MixedPrecInverterTest ../parameter/tests/MixedPrecInverterTest.param Nodes="2 2 1 1" 
# [2022-01-30 22:19:14] INFO: Initializing MPI with (4 proc) 
# [2022-01-30 22:19:14] INFO: Reading parameters from file :: ../parameter/tests/MixedPrecInverterTest.param 
# [2022-01-30 22:19:14] INFO: # PARAM :: Lattice = 64 64 64 32 
# [2022-01-30 22:19:14] INFO: # PARAM :: Nodes = 2 2 1 1 
# [2022-01-30 22:19:14] INFO: # PARAM :: Topology = 0 0 0 0  (default) 
# [2022-01-30 22:19:14] INFO: # PARAM :: beta = 3.85 
# [2022-01-30 22:19:14] INFO: # PARAM :: Gaugefile = l328f21b6260m00405m0810a_4000. 
# [2022-01-30 22:19:14] INFO: # PARAM :: endianness = auto (default) 
# [2022-01-30 22:19:14] INFO: # PARAM :: conf_nr = 0 
# [2022-01-30 22:19:14] INFO: # PARAM :: no_pf = 1 (default) 
# [2022-01-30 22:19:14] INFO: # PARAM :: no_md = 10 
# [2022-01-30 22:19:14] INFO: # PARAM :: no_step_sf = 5 
# [2022-01-30 22:19:14] INFO: # PARAM :: no_sw = 10 
# [2022-01-30 22:19:14] INFO: # PARAM :: step_size = 0.02 
# [2022-01-30 22:19:14] INFO: # PARAM :: mu0 = 0 (default) 
# [2022-01-30 22:19:14] INFO: # PARAM :: integrator = 0 (default) 
# [2022-01-30 22:19:14] INFO: # PARAM :: residue = 1e-08 
# [2022-01-30 22:19:14] INFO: # PARAM :: residue_force = 1e-07 (default) 
# [2022-01-30 22:19:14] INFO: # PARAM :: cgMax = 6500 
# [2022-01-30 22:19:14] INFO: # PARAM :: residue_meas = 1e-12 (default) 
# [2022-01-30 22:19:14] INFO: # PARAM :: cgMax_meas = 20000 (default) 
# [2022-01-30 22:19:14] INFO: # PARAM :: always_acc = 0 
# [2022-01-30 22:19:14] INFO: # PARAM :: cgMixedPrec = 0 (default) 
# [2022-01-30 22:19:14] INFO: # PARAM :: cgMixedPrec_delta = 0.1 (default) 
# [2022-01-30 22:19:14] INFO: # PARAM :: no_updates = 100 
# [2022-01-30 22:19:14] INFO: # PARAM :: write_every = 10 
# [2022-01-30 22:19:14] INFO: # PARAM :: rat_file = ../parameter/sample_force_test.rat 
# [2022-01-30 22:19:14] INFO: # PARAM :: mass_ud = 0.00591 
# [2022-01-30 22:19:14] INFO: # PARAM :: mass_s = 0.0591 
# [2022-01-30 22:19:14] INFO: # PARAM :: rand_file = rand 
# [2022-01-30 22:19:14] INFO: # PARAM :: seed = 1337 
# [2022-01-30 22:19:14] INFO: # PARAM :: rand_flag = 0 
# [2022-01-30 22:19:14] INFO: # PARAM :: load_conf = 1 
# [2022-01-30 22:19:14] INFO: Reading parameters from file :: ../parameter/sample_force_test.rat 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_inv_1f_const = 9.17375 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_inv_1f_num = -1.29981e-05 -5.96418e-05 -0.000184191 -0.000511036 -0.00136684 -0.00361064 -0.00953178 -0.0254009 -0.0693287 -0.199112 -0.635954 -2.55302 -17.6983 -797.129 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_inv_1f_den = 0.000385799 0.00182818 0.00505325 0.0116746 0.0250164 0.0518228 0.105833 0.215495 0.441744 0.923961 2.02272 4.90755 15.4367 126.178 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_1f_const = 0.109007 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_1f_num = 0.00398935 0.00591784 0.00844626 0.012385 0.0185836 0.0283082 0.043583 0.0678068 0.107123 0.174024 0.298749 0.574735 1.42186 6.9582 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_1f_den = 0.000138408 0.00113133 0.00355861 0.00863395 0.0189013 0.0395344 0.0810417 0.165015 0.336995 0.698104 1.4959 3.456 9.55272 45.2672 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_bar_1f_const = 0.00980362 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_bar_1f_num = 0.131209 0.0674017 0.0625201 0.0677341 0.078548 0.0941156 0.114958 0.143065 0.183652 0.251687 0.401263 0.961597 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_bar_1f_den = 6.43709e-05 0.00115723 0.00423957 0.0114183 0.0276229 0.0640767 0.146516 0.335649 0.784142 1.93175 5.45804 23.4914 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_inv_2f_const = 1 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_inv_2f_num = -1.38018e-07 -4.89e-07 -1.14218e-06 -2.34991e-06 -4.58681e-06 -8.70325e-06 -1.61605e-05 -2.92986e-05 -5.13842e-05 -8.56779e-05 -0.000132033 -0.00017989 -0.000201181 -0.000151436 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_inv_2f_den = 1.78866e-06 8.54739e-06 2.20938e-05 4.58944e-05 8.5928e-05 0.000151936 0.000259122 0.000429911 0.000694306 0.00108511 0.00162121 0.00227313 0.00292279 0.00336784 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_2f_const = 1 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_2f_num = 5.04302e-06 8.86749e-06 1.30209e-05 1.85618e-05 2.63353e-05 3.726e-05 5.22885e-05 7.20776e-05 9.61303e-05 0.000121134 0.000138793 0.000135563 9.98678e-05 3.95277e-05 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_2f_den = 9.23641e-07 6.31465e-06 1.79166e-05 3.87089e-05 7.3944e-05 0.000132279 0.000227376 0.000379723 0.000617586 0.00097403 0.00147393 0.00210398 0.00277081 0.00328762 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_bar_2f_const = 1 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_bar_2f_num = 6.57678e-05 7.13607e-05 8.28982e-05 0.000101005 0.00012633 0.000158917 0.000196773 0.000233137 0.000252859 0.000232438 0.00015592 5.15364e-05 
# [2022-01-30 22:19:14] INFO: # PARAM :: r_bar_2f_den = 7.60896e-07 7.24698e-06 2.24932e-05 5.17881e-05 0.000105069 0.000199655 0.00036392 0.000640004 0.0010788 0.00171161 0.0024822 0.0031722 
# [2022-01-30 22:19:14] INFO: > Running on: 
# [2022-01-30 22:19:14] INFO: [Rank 0] > p001 CPU_3 GPU_5; MPI: world_rank=0, node_rank=0, coord: ( 0 0 0 0 ) 
# [2022-01-30 22:19:14] INFO: [Rank 1] > p001 CPU_0 GPU_6; MPI: world_rank=1, node_rank=1, coord: ( 0 1 0 0 ) 
# [2022-01-30 22:19:14] INFO: [Rank 3] > p001 CPU_1 GPU_85; MPI: world_rank=3, node_rank=3, coord: ( 1 1 0 0 ) 
# [2022-01-30 22:19:14] INFO: [Rank 2] > p001 CPU_2 GPU_84; MPI: world_rank=2, node_rank=2, coord: ( 1 0 0 0 ) 
# [2022-01-30 22:19:14] INFO: > Is MPI CUDA-aware? @compilation YES, @runtime YES 
# [2022-01-30 22:19:14] INFO: > GPU compute capability: 60 
# [2022-01-30 22:19:14] WARN: Cannot determine for which compute capability the code was compiled! 
# [2022-01-30 22:19:14] DEBUG: > Collecting neighbor information... 
# [2022-01-30 22:19:14] DEBUG: > Neighbor information collected! 
# [2022-01-30 22:19:14] INFO: > Checking support for P2P (Peer-to-Peer) and UVA (Unified Virtual Addressing): 
# [2022-01-30 22:19:14] INFO: [Rank 3] > p001 GPU_85(Tesla P100-SXM2-16GB): P2P YES; UVA YES 
# [2022-01-30 22:19:14] INFO: [Rank 1] > p001 GPU_6(Tesla P100-SXM2-16GB): P2P YES; UVA YES 
# [2022-01-30 22:19:14] INFO: [Rank 0] > p001 GPU_5(Tesla P100-SXM2-16GB): P2P YES; UVA YES 
# [2022-01-30 22:19:14] INFO: [Rank 2] > p001 GPU_84(Tesla P100-SXM2-16GB): P2P YES; UVA YES 
# [2022-01-30 22:19:14] INFO: Initialize Indexer with HaloDepth = 4 
# [2022-01-30 22:19:15] DEBUG: [Rank 1] Local size without Halos: 32 32 64 32 
# [2022-01-30 22:19:15] DEBUG: [Rank 1] Local size with Halos: 40 40 64 32 
# [2022-01-30 22:19:15] DEBUG: [Rank 3] Local size without Halos: 32 32 64 32 
# [2022-01-30 22:19:15] DEBUG: [Rank 3] Local size with Halos: 40 40 64 32 
# [2022-01-30 22:19:15] DEBUG: [Rank 0] Local size without Halos: 32 32 64 32 
# [2022-01-30 22:19:15] DEBUG: [Rank 0] Local size with Halos: 40 40 64 32 
# [2022-01-30 22:19:15] INFO: Running mixed precision inverter test 
# [2022-01-30 22:19:15] INFO: testing float-half 
# [2022-01-30 22:19:15] DEBUG: [Rank 2] Local size without Halos: 32 32 64 32 
# [2022-01-30 22:19:15] DEBUG: [Rank 2] Local size with Halos: 40 40 64 32 
# [2022-01-30 22:19:17] INFO: Randomize spinors 
# [2022-01-30 22:19:30] INFO: CG: # iterations 2465 residual: 9.08733e-09 
# [2022-01-30 22:19:30] INFO: dot1 (0.695072,0) dot2 (1.25874e+07,0) 
# [2022-01-30 22:19:30] INFO: 5.52196e-08 
# [2022-01-30 22:19:30] INFO: relative error of (D^+D) * (D^+D)^-1 * phi - phi : 5.52196e-08 
# [2022-01-30 22:19:30] INFO: Time for inversion: 13.344s 
# [2022-01-30 22:19:30] INFO: Inverter test: passed 
# [2022-01-30 22:19:31] INFO: testing double-float 
# [2022-01-30 22:19:34] INFO: Randomize spinors 
# [2022-01-30 22:19:54] INFO: CG: # iterations 2117 residual: 9.91591e-09 
# [2022-01-30 22:19:55] INFO: dot1 (0.124816,3.41503e-21) dot2 (1.25874e+07,3.0253e-14) 
# [2022-01-30 22:19:55] INFO: 9.91591e-09 
# [2022-01-30 22:19:55] INFO: relative error of (D^+D) * (D^+D)^-1 * phi - phi : 9.91591e-09 
# [2022-01-30 22:19:55] INFO: Time for inversion: 20.088s 
# [2022-01-30 22:19:55] INFO: Inverter test: passed 
# [2022-01-30 22:19:55] INFO: testing double-half 
# [2022-01-30 22:19:59] INFO: Randomize spinors 
# [2022-01-30 22:20:12] INFO: CG: # iterations 2468 residual: 9.9091e-09 
# [2022-01-30 22:20:12] INFO: dot1 (0.206524,9.49345e-22) dot2 (1.25874e+07,3.0253e-14) 
# [2022-01-30 22:20:12] INFO: 1.64072e-08 
# [2022-01-30 22:20:12] INFO: relative error of (D^+D) * (D^+D)^-1 * phi - phi : 1.64072e-08 
# [2022-01-30 22:20:12] INFO: Time for inversion: 13.707s 
# [2022-01-30 22:20:12] INFO: Inverter test: passed 
# [2022-01-30 22:20:12] INFO: Finalize CommunicationBase 
```
In your log it says that you are out of memory. Did you maybe run multiple tests at the same time on this node?

**Comment by clarkedavida** [comment]
Well that is very strange. I was using the test script, so nothing else should have been running. When I ran the script a second time, it passed. I'm not sure what happened...

OK I will continue with the tests tomorrow. So far, so good.

**Comment by luhuhis** [comment]
For AMD, cmake still wants to use nvcc to compile:
`nvcc fatal   : Unknown option '--amdgpu-target=gfx90'`

**Comment by philomat** [comment]
Using hip for AMD I had to add additional compiler parameters (see also my hip branch):

`set(HIP_HIPCC_FLAGS "-O3 -std=c++17 -D__HIP_PLATFORM_AMD__ --amdgpu-target=gfx906,gfx908 -fgpu-rdc")
set(CMAKE_EXE_LINKER_FLAGS "-O3 -fgpu-rdc --hip-link")`

I guess for Nvidia you have to include in your CMAKE_CUDA_FLAGS a -D__HIP_PLATFORM_NVIDIA__

**Comment by lukas-mazur** [comment]
> Using hip for AMD I had to add additional compiler parameters (see also my hip branch):
> 
> `set(HIP_HIPCC_FLAGS "-O3 -std=c++17 -D__HIP_PLATFORM_AMD__ --amdgpu-target=gfx906,gfx908 -fgpu-rdc") set(CMAKE_EXE_LINKER_FLAGS "-O3 -fgpu-rdc --hip-link")`
> 
> I guess for Nvidia you have to include in your CMAKE_CUDA_FLAGS a -D__HIP_PLATFORM_NVIDIA__

I did that for Nvidia as well in [line 134 in the CMakelist.txt](https://github.com/LatticeQCD/SIMULATeQCD/blob/hip_and_cuda/CMakeLists.txt#L134) and on my Arch linux system it compiles. So I'm not sure what is going on there..

**Comment by luhuhis** [comment]
```
export HIP_PATH=/opt/rocm-4.5.2/hip
export HIP_PLATFORM=amd

cmake ../SIMULATeQCD/ \
-DARCHITECTURE="gfx906,gfx908" \
-DUSE_GPU_AWARE_MPI=ON \
-DUSE_GPU_P2P=OFF \
-DBACKEND="hip_amd" \
```
with this it starts to compile on the Bielefeld cluster, but complains about a missing file:
`/home/altenkort/code_build/SIMULATeQCD/SIMULATeQCD/src/base/communication/../math/grnd.h:8:10: fatal error: 'curand_kernel.h' file not found`

it would be good to handle these two env variables as CMake parameters. the first one should be a user input, the second one can be inferred from "-DBACKEND"
```
export HIP_PATH=/opt/rocm-4.5.2/hip
export HIP_PLATFORM=amd
```

**Comment by lukas-mazur** [comment]
> ```
> export HIP_PATH=/opt/rocm-4.5.2/hip
> export HIP_PLATFORM=amd
> 
> cmake ../SIMULATeQCD/ \
> -DARCHITECTURE="gfx906,gfx908" \
> -DUSE_GPU_AWARE_MPI=ON \
> -DUSE_GPU_P2P=OFF \
> -DBACKEND="hip_amd" \
> ```
> 
> with this it starts to compile on the Bielefeld cluster, but complains about a missing file: `/home/altenkort/code_build/SIMULATeQCD/SIMULATeQCD/src/base/communication/../math/grnd.h:8:10: fatal error: 'curand_kernel.h' file not found`
> 
> it would be good to handle these two env variables as CMake parameters. the first one should be a user input, the second one can be inferred from "-DBACKEND"
> 
> ```
> export HIP_PATH=/opt/rocm-4.5.2/hip
> export HIP_PLATFORM=amd
> ```
Ah, that's already helpful, thanks! You can already pass the first env variable with `-DHIP_PATH`. For the second one I don't know  how to use it, i.e. I don't know which cmake funktion is interested in `HIP_PLATFORM` variable.

**Comment by luhuhis** [comment]
I think you can simply require that the user provides -DHIP_PLATFORM, and then I think there's a cmake function that let's you export environment variables, i.e. do the equivalent of "export HIP_PLATFORM=...".

**Comment by lukas-mazur** [comment]
> ```
> export HIP_PATH=/opt/rocm-4.5.2/hip
> export HIP_PLATFORM=amd
> 
> cmake ../SIMULATeQCD/ \
> -DARCHITECTURE="gfx906,gfx908" \
> -DUSE_GPU_AWARE_MPI=ON \
> -DUSE_GPU_P2P=OFF \
> -DBACKEND="hip_amd" \
> ```
> 
> with this it starts to compile on the Bielefeld cluster, but complains about a missing file: `/home/altenkort/code_build/SIMULATeQCD/SIMULATeQCD/src/base/communication/../math/grnd.h:8:10: fatal error: 'curand_kernel.h' file not found`

I have removed `curand_kernel.h` from the hip backend. Can you try to compile it again? @luhuhis

**Comment by luhuhis** [comment]
But if the cluster supports both AMD and NVIDIA, then I guess the user has to set this accordingly before calling (c)make? 

This is the next file that needs to be excluded:
```/home/altenkort/code_build/SIMULATeQCD/SIMULATeQCD/src/modules/gaugeFixing/../../base/math/../communication/siteComm.h:16:10: fatal error: 'nvToolsExt.h' file not found```

**Comment by lukas-mazur** [comment]
> But if the cluster supports both AMD and NVIDIA, then I guess the user has to set this accordingly before calling (c)make?

Yes, but there should be some kind of scripts or modules available on the cluster, which allow you to switch between these environments, e.g. "module load hip_nvidia" and "module load hip_amd".

> This is the next file that needs to be excluded: `/home/altenkort/code_build/SIMULATeQCD/SIMULATeQCD/src/modules/gaugeFixing/../../base/math/../communication/siteComm.h:16:10: fatal error: 'nvToolsExt.h' file not found`

Alright, I guess there will be more of that. These kind of errors can be fixed by doing:
```C++
#ifdef USE_CUDA
#include <cuda_specific_header.h>
#endif

#ifdef USE_HIP
#include <hip_specific_header.h>
#endif

#ifdef USE_HIP_NVIDIA
#include <hip_nvidia_specific_header.h>
#endif

#ifdef USE_HIP_AMD
#include <hip_amd_specific_header.h>
#endif
```

**Comment by luhuhis** [comment]
With the new commits I get these errors while compiling the RHMC:

```
c++: error: unrecognized command-line option ‘-fgpu-rdc’
c++: error: unrecognized command-line option ‘--offload-arch=gfx900’
c++: error: unrecognized command-line option ‘--offload-arch=gfx906’
c++: error: unrecognized command-line option ‘--offload-arch=gfx908’
c++: error: unrecognized command-line option ‘--offload-arch=gfx90a’
c++: error: unrecognized command-line option ‘--offload-arch=gfx1030’
```
I also get a lot of warnings of this type:

`warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]`

**Comment by luhuhis** [comment]
Although it took forever, I got it to compile and link. Especially the linking took suprisingly long. 
I was just missing two env variables, CC and CXX. So in summary, this works on influx in Bielefeld:
`export HIP_PATH=/opt/rocm-4.5.2/hip
export HIP_PLATFORM=amd
export CC=/opt/rocm/llvm/bin/clang
export CXX=/opt/rocm/llvm/bin/clang++

cmake ../SIMULATeQCD/ \
-DARCHITECTURE="gfx906" \
-DUSE_GPU_AWARE_MPI=ON \
-DUSE_GPU_P2P=OFF \
-DBACKEND="hip_amd" \

make -j RHMC`

The are still many warnings of not unrolled loops, but I guess these are harmless.

**Comment by luhuhis** [comment]
Compiling the gradient flow does not work yet, many errors are thrown, see attached file
[flow.log](https://github.com/LatticeQCD/SIMULATeQCD/files/8008121/flow.log)

**Comment by lukas-mazur** [comment]
> Compiling the gradient flow does not work yet, many errors are thrown, see attached file [flow.log](https://github.com/LatticeQCD/SIMULATeQCD/files/8008121/flow.log)

Now gradientFlow also compiles for AMD. 
I didn't run all tests yet, though

**Comment by lukas-mazur** [comment]
All cuda multi- and single-gpu tests have passed.

**Pull request merged**
