### PR TITLE
Updated wilson corr

### PR DESCRIPTION
**Pull request by RasmusNL**
The branch contains updates to the wilson line correlator such that hyp smearing can be used and a maximum radius can be specified.

A maximal center gauge fixing has been implemented into the gauge fixing class. 
The gauge fixing uses a QR algorithm defined in a class called matrix4x4_notSym.h

A quick wilon loop was also created that is now in the experimental folder.

test for the wilson line and maximal center gauge fixing has been made. 

All test has been run. The following error was seen on main and on branch.
OUT_HBOR_multiple_test:4 total processes failed to start
OUT_HBOR_multiple_test:4 total processes failed to start
OUT_HBOR_multiple_test:4 total processes failed to start
OUT_RndMultipleTest:2 total processes failed to start

though no new errors has appeared, which makes sense as the changes should not affect other applications.

Also the checksum for milc does not exist, and is therefore commented out for now.

Regards Rasmus

### CODE REVIEW

**Comment by dbollweg** [comment]
Looks almost ready to merge. Two things: you commented out the Git Hash in the mpi CommunicationBase constructor. Is that causing issues or can you re-enable that? And: you commented out the checksum check for milc configurations. Can you instead make it optional so that the check is on by default but you can turn it off for your use-case?

**Review by dbollweg — CHANGES_REQUESTED** [review]
Looks good to me, two small things: Can you include the git hash in the communicationbase constructor again and make the checksum check for milc configurations optional with a default setting to perform the checksum test?

**Comment by dbollweg** [comment]
Should've read your description more closely... Forget about my milc checksum comment.

**Review by lukas-mazur — APPROVED** [review]
It looks good!

**Review by dbollweg — APPROVED** [review]

**Pull request merged**
