### PR TITLE
Hotfix/parameter

### LINKED ISSUE #51: Throw an error when a parameter is given that does not exist
I think this can be done by a few lines in /src/base/IO/parameterManagement.cpp after both lines 35 and 41. Throw an error when no match has occurred.

### PR DESCRIPTION
**Pull request by luhuhis**
this resolves #51

### CODE REVIEW

**Comment by dbollweg** [comment]
With your updates, comments are now causing an error to be thrown:
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] # #residue is not a known parameter.

# [2022-01-25 17:25:10] INFO: Initializing MPI with (1 proc)
# [2022-01-25 17:25:10] INFO: Reading parameters from file :: ../parameter/applications/rhmc.param
# [2022-01-25 17:25:10] FATAL: [Rank 0] # #residue is not a known parameter.

**Review by dbollweg — CHANGES_REQUESTED** [review]
Comments in the parameter file now cause an error to be thrown.

**Comment by luhuhis** [comment]
I fixed it

**Comment by lukas-mazur** [comment]
Sounds good. I will run some single-gpu tests.

**Comment by lukas-mazur** [comment]
Many Tests are failing now. 
These are the Tests which fail:
```
optirun ./_correlatorTest ../parameter/tests/correlatorTest.param Nodes=1 1 1 1
# [2022-01-25 20:31:02] FATAL: [Rank 0] # Domain is not a known parameter.

optirun ./_cudaIpcTest ../parameter/tests/cudaIpcTest.param Nodes=1 1 1 1
# [2022-01-25 20:31:09] FATAL: [Rank 0] # always_acc is not a known parameter.

optirun ./_DslashMultiTest ../parameter/tests/DslashMultiTest.param Nodes=1 1 1 1
# [2022-01-25 20:31:20] FATAL: [Rank 0] # HDR_VERSION is not a known parameter.

optirun ./_HBOR_multiple_test ../parameter/tests/HBOR_multiple_test.param Nodes=1 1 1 1
# [2022-01-25 20:32:29] FATAL: [Rank 0] # HDR_VERSION is not a known parameter.

optirun ./_hisqForceImagmu ../parameter/tests/hisqForceImagMu.param Nodes=1 1 1 1
# [2022-01-25 20:32:33] FATAL: [Rank 0] # always_acc is not a known parameter.

optirun ./_hisqForce ../parameter/tests/hisqForce.param Nodes=1 1 1 1
# [2022-01-25 20:32:36] FATAL: [Rank 0] # always_acc is not a known parameter.

optirun ./_hisqSmearingImagmuTest ../parameter/tests/hisqSmearingTest.param Nodes=1 1 1 1
# [2022-01-25 20:32:40] FATAL: [Rank 0] # HDR_VERSION is not a known parameter.

optirun ./_hisqSmearingMultiCreate ../parameter/run.param Nodes=1 1 1 1
# [2022-01-25 20:32:43] FATAL: [Rank 0] # always_acc is not a known parameter.

optirun ./_hisqSmearingTest ../parameter/tests/hisqSmearingTest.param Nodes=1 1 1 1
# [2022-01-25 20:32:47] FATAL: [Rank 0] # HDR_VERSION is not a known parameter.

optirun ./_InverterTest ../parameter/tests/InverterTest.param Nodes=1 1 1 1
# [2022-01-25 20:32:50] FATAL: [Rank 0] # always_acc is not a known parameter.

optirun ./_LinkPathTest ../parameter/tests/LinkPathTest.param Nodes=1 1 1 1
# [2022-01-25 20:32:54] FATAL: [Rank 0] # HDR_VERSION is not a known parameter.

optirun ./_MixedPrecInverterTest ../parameter/tests/MixedPrecInverterTest.param Nodes=1 1 1 1
# [2022-01-25 20:32:57] FATAL: [Rank 0] # always_acc is not a known parameter.

optirun ./_PureGaugeHmcTest ../parameter/tests/pure_gauge_hmc.param Nodes=1 1 1 1
# [2022-01-25 20:33:03] FATAL: [Rank 0] # config_nr is not a known parameter.

optirun ./_rhmcTest ../parameter/tests/rhmcTest.param Nodes=1 1 1 1
# [2022-01-25 20:33:06] FATAL: [Rank 0] # config_nr is not a known parameter.
```

I did not test these Tests, because I don't know which parameter files they need:
```
_DslashImagmuTest
_RndMultipleTest
_hisqSmearingMulti
_HBOR_single_test
```

**Review by lukas-mazur — CHANGES_REQUESTED** [review]
Please solve this @luhuhis

**Comment by luhuhis** [comment]
Well, this just means that all of these tests have parameter files that are actually not used at all. Maybe the corresponding experts of the tests should also have a look at this.

**Comment by clarkedavida** [comment]
If I were you, I would just remove these unused parameters now. These tests have had many developers over the years, and I'm not sure everyone will take responsibility and look into them again.

**Comment by luhuhis** [comment]
Yeah you're right. I'll do that once my job to run all tests is finally scheduled to run...

**Comment by luhuhis** [comment]
Actually, these errors stem from read ins of header files of gauge configurations, which apparently also use the same readstream() function.

**Review by lukas-mazur — CHANGES_REQUESTED** [review]
I ran the same tests as before and some are still failing with:
```
optirun ./_correlatorTest ../parameter/tests/correlatorTest.param Nodes=1 1 1 1
  what():  [Rank 0] Problem opening norm file.

optirun ./_gfixTestMulti ../parameter/tests/gfixTestMulti.param Nodes=1 1 1 1
  what():  [Rank 0] Error reading header of gfixTestSingle_conf

optirun ./_HBOR_multiple_test ../parameter/tests/HBOR_multiple_test.param Nodes=1 1 1 1
  what():  [Rank 0] Error reading header of config_HBORTestRD

optirun ./_hisqForceImagmu ../parameter/tests/hisqForceImagMu.param Nodes=1 1 1 1
  what():  [Rank 0] Lattice is either not a known parameter or its value could not be cast into the
correct data type.

optirun ./_hisqForce ../parameter/tests/hisqForce.param Nodes=1 1 1 1
  what():  [Rank 0] Lattice is either not a known parameter or its value could not be cast into the
correct data type.

optirun ./_hisqSmearingTest ../parameter/tests/hisqSmearingTest.param Nodes=1 1 1 1
  what():  [Rank 0] Error reading header of ../test_conf/smearing_reference_conf

optirun ./_rhmcTest_4pf ../parameter/tests/rhmcTest_4pf.param Nodes=1 1 1 1
  what():  [Rank 0] Lattice is either not a known parameter or its value could not be cast into the
correct data type.

optirun ./_rhmcTest ../parameter/tests/rhmcTest.param Nodes=1 1 1 1
  what():  [Rank 0] Lattice is either not a known parameter or its value could not be cast into the
correct data type.

optirun ./_PureGaugeHmcTest ../parameter/tests/PureGaugeHmcTest.param Nodes=1 1 1 1
  what():  [Rank 0] Nodes is either not a known parameter or its value could not be cast into the correct data type.
```

**Comment by luhuhis** [comment]
I double checked; for me everything works. I run all tests with the /scripts/jobscript_TEST_run script.

**Comment by luhuhis** [comment]
Okay, now I can also reproduce the error. It happens when two different parameter files are read in, and one of the corresponding parameter classes does not know about the "Lattice" or "Nodes" parameter for example (like in the RationalCoeff class). The command line arguments are of course considered for all parameter files that are read in, and so an error is thrown.

**Comment by luhuhis** [comment]
```
optirun ./_correlatorTest ../parameter/tests/correlatorTest.param Nodes=1 1 1 1
  what():  [Rank 0] Problem opening norm file.
```
I can't reproduce this error. Did you copy the files /parameter/UA_s8t4.norm  /parameter/US_s8t4.norm to the directory where you run this test?

```
optirun ./_gfixTestMulti ../parameter/tests/gfixTestMulti.param Nodes=1 1 1 1
  what():  [Rank 0] Error reading header of gfixTestSingle_conf
```

This one I can't reproduce either. Did you run gfixTestSingle before running this? It creates the necessary configuration.

```
optirun ./_HBOR_multiple_test ../parameter/tests/HBOR_multiple_test.param Nodes=1 1 1 1
  what():  [Rank 0] Error reading header of config_HBORTestRD
```
This one as well. Did you run HBOR_single_test before?

```
optirun ./_hisqForceImagmu ../parameter/tests/hisqForceImagMu.param Nodes=1 1 1 1
  what():  [Rank 0] Lattice is either not a known parameter or its value could not be cast into the
correct data type.
```
This one is caused by the line `rat.readfile(commBase, rhmc_param.rat_file(), argc, argv);`. I guess one should omit argc and argv here, such that the `rat` does not read parameters from the command line.

```
optirun ./_hisqForce ../parameter/tests/hisqForce.param Nodes=1 1 1 1
  what():  [Rank 0] Lattice is either not a known parameter or its value could not be cast into the
correct data type.
```
See above, same fix.

```
optirun ./_hisqSmearingTest ../parameter/tests/hisqSmearingTest.param Nodes=1 1 1 1
  what():  [Rank 0] Error reading header of ../test_conf/smearing_reference_conf
```
This conf is missing in the current branch, which is why this error is thrown.

```
optirun ./_rhmcTest_4pf ../parameter/tests/rhmcTest_4pf.param Nodes=1 1 1 1
  what():  [Rank 0] Lattice is either not a known parameter or its value could not be cast into the
correct data type.
```
Same "error" in the code as in hisqForceImagMu.

```
optirun ./_rhmcTest ../parameter/tests/rhmcTest.param Nodes=1 1 1 1
  what():  [Rank 0] Lattice is either not a known parameter or its value could not be cast into the
correct data type.
```
Same "error" in the code as in hisqForceImagMu.


```
optirun ./_PureGaugeHmcTest ../parameter/tests/PureGaugeHmcTest.param Nodes=1 1 1 1
  what():  [Rank 0] Nodes is either not a known parameter or its value could not be cast into the correct data type.
```

Here I have no idea what is wrong. i can't reproduce this at all.

**Review by lukas-mazur — APPROVED** [review]

**Comment by lukas-mazur** [comment]
Ok, the single GPU tests work. I have also added a prototype of a test script for single gpu in the script folder. 

In my opinion we can merge this branch.

**Review by dbollweg — APPROVED** [review]
lgtm

**Pull request merged**
